"""make_sample.py: build every layer the viewer can draw, with zero downloads.

The real datasets (NIST NASCTN CBRS SEA, NIST I/Q libraries) are multi-GB and
not in this repo. This script fabricates a small version of each one and runs
the normal ingest pipeline over it, so a fresh clone gets all four databases:

    iq.duckdb        one SigMF capture   (sigmf_io + iq_ingest)
    spectrum.duckdb  Summaries + pyramid (build_db)
    psd.duckdb       power spectral density per sensor (psd_ingest)
    pfp.duckdb       periodic frame power per channel  (pfp_ingest)

Without the CBRS three, serve.py starts with "spectrum.duckdb not found --
CBRS monitoring disabled" and the sensor dropdown, the statistic buttons and
the PSD/PFP layers have nothing behind them. That message used to point here
while this script built only the IQ layer, so following it changed nothing.

    python examples/make_sample.py           # all four layers
    python examples/make_sample.py --iq      # just the IQ capture
    python examples/make_sample.py --cbrs    # just the CBRS three
    python serve.py                          # http://127.0.0.1:8090

Everything here is fake data generated by numpy: it identifies no real device,
no real deployment and no real spectrum occupancy.
"""

import argparse
import json
import os
import subprocess
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
INGEST = os.path.join(ROOT, "ingest")
SAMPLE_DIR = os.path.join(HERE, "sample_data")
CBRS_DIR = os.path.join(SAMPLE_DIR, "cbrs")

FS = 2_000_000        # 2 Msps
FC = 2_412_000_000    # 2.412 GHz (Wi-Fi ch 1-ish centre, purely cosmetic)
DUR = 0.5             # seconds  -> 1e6 complex samples (~8 MB cf32)

# ---- CBRS demo shape --------------------------------------------------
# Two sensors so the sensor dropdown has something to switch between, and one
# quieter than the other so switching visibly changes the picture.
SENSORS = ("DEMO-Directional", "DEMO-Omni")
DAYS = ("2024-03-04", "2024-03-05", "2024-03-06")
# The real NASCTN SEA channel grid: 18 x 10 MHz centred on 3535 + 10k MHz.
# This used to be 3550 + 10k, half a channel off the real thing -- which put the
# demo's PFP channels on centres the viewer never asks for, so the frame layer
# 404'd on every request and a fresh clone could not reach the deepest layer at
# all. It also disagreed with PSD_F0/PSD_DF/PSD_NF three lines below, which have
# always described the 3535-grid band.
CHANNELS = [3535.0 + 10.0 * i for i in range(18)]   # 3535..3705 MHz, 10 MHz each
SUMMARY_STEP = 300      # seconds between Summaries rows
PSD_PER_DAY = 12        # PSD captures per sensor per day
PFP_PER_DAY = 8         # PFP frames per sensor per channel per day

# These must match the ingest scripts, which quantize against them. Values
# outside the range are clipped, which would flatten the demo's structure.
PSD_F0, PSD_DF, PSD_NF = 3530.04e6, 80e3, 2250       # psd_ingest F0/DF/NF
PSD_QMIN, PSD_QMAX = -180.0, -90.0                   # psd_ingest QMIN/QMAX
PFP_NPOS = 560                                       # pfp_ingest NPOS
PFP_QMIN, PFP_QMAX = -130.0, -10.0                   # pfp_ingest QMIN/QMAX


def synth():
    """A complex baseband signal with structure that reads clearly on an STFT."""
    n = int(FS * DUR)
    t = np.arange(n) / FS
    rng = np.random.default_rng(0)
    x = (rng.standard_normal(n) + 1j * rng.standard_normal(n)) * 0.02  # noise floor

    # 1) steady carrier at +400 kHz
    x += 0.5 * np.exp(2j * np.pi * 400_000 * t)

    # 2) frequency-hopping tone: steps across the band every 50 ms
    hops = [-700_000, -300_000, 100_000, 500_000, 800_000, 200_000, -500_000, -100_000, 600_000, 0]
    seg = n // len(hops)
    for i, f in enumerate(hops):
        s = slice(i * seg, (i + 1) * seg)
        x[s] += 0.6 * np.exp(2j * np.pi * f * t[s])

    # 3) periodic wideband bursts (10 ms on / 40 ms off): LTE/Wi-Fi-like TDD
    burst = (np.mod(t, 0.05) < 0.010)
    wb = (rng.standard_normal(n) + 1j * rng.standard_normal(n)) * 0.5
    # keep the burst inside +/-900 kHz so its edges are visible against the band
    x += burst * wb

    return x.astype(np.complex64)


def write_sigmf(x):
    os.makedirs(SAMPLE_DIR, exist_ok=True)
    base = os.path.join(SAMPLE_DIR, "demo_signal")
    x.tofile(base + ".sigmf-data")
    meta = {
        "global": {
            "core:datatype": "cf32_le",
            "core:sample_rate": FS,
            "core:version": "1.0.0",
            "core:description": "Synthetic demo signal (numpy), not real RF.",
        },
        "captures": [{"core:sample_start": 0, "core:frequency": FC}],
        "annotations": [],
    }
    with open(base + ".sigmf-meta", "w") as f:
        json.dump(meta, f, indent=2)
    return base + ".sigmf-meta"


# ---- CBRS: the three monitoring layers --------------------------------

def _load(sensor, ch_mhz, hour):
    """Occupancy 0..1 for one channel at one time of day.

    The demo is more useful when it looks like something: a fixed-wireless
    deployment loading the upper channels on a daily cycle, and the lower
    channels near-empty because that is the part of the band CBRS protects.
    """
    diurnal = 0.5 - 0.5 * np.cos(2 * np.pi * (hour - 4.0) / 24.0)   # peaks ~16:00
    if sensor == "DEMO-Directional":
        # Pointed at a busy deployment on 3620-3660.
        band = np.exp(-((ch_mhz - 3640.0) / 22.0) ** 2)
        return float(np.clip(0.15 + 0.85 * band * diurnal, 0, 1))
    # Omni: sees less of it, and spread wider.
    band = np.exp(-((ch_mhz - 3630.0) / 45.0) ** 2)
    return float(np.clip(0.05 + 0.40 * band * diurnal, 0, 1))


def _radar(day_index, seconds, ch_mhz):
    """Occasional short bursts low in the band, like the incumbent radar the
    CBRS ESC exists to detect. Deterministic, so the demo looks the same twice."""
    if ch_mhz > 3580.0:
        return 0.0
    rng = np.random.default_rng(int(day_index * 1000 + seconds // 1800))
    if rng.random() > 0.06:
        return 0.0
    return float(rng.uniform(0.6, 1.0))


def write_summaries(path):
    """Summaries CSV -> build_db.py -> spectrum.duckdb (the zoomed-out layer)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    rng = np.random.default_rng(11)
    rows = []
    for di, day in enumerate(DAYS):
        for sec in range(0, 86400, SUMMARY_STEP):
            hour = (sec / 3600.0) % 24.0
            hh, mm, ss = sec // 3600, (sec % 3600) // 60, sec % 60
            stamp = f"{day} {hh:02d}:{mm:02d}:{ss:02d}+00"
            for sensor in SENSORS:
                for ch in CHANNELS:
                    occ = max(_load(sensor, ch, hour), _radar(di, sec, ch))
                    # Noise floor when empty, rising toward a loaded channel.
                    mean = -100.0 + 32.0 * occ + rng.normal(0, 0.8)
                    median = mean + rng.uniform(-1.5, 1.5)
                    mx = mean + 6.0 + 9.0 * occ + abs(rng.normal(0, 1.5))
                    rows.append((sensor, ch, stamp,
                                 round(mx, 2), round(median, 2), round(mean, 2)))
    with open(path, "w", newline="") as f:
        f.write("sensor_name,channel_frequency_mhz,timestamp,max,median,mean\n")
        for r in rows:
            f.write(",".join(str(v) for v in r) + "\n")
    return len(rows)


def _spectrum(sensor, day_index, sec, rng):
    """One 2250-bin PSD trace in dBm/Hz, shaped by which channels are busy."""
    f_mhz = (PSD_F0 + PSD_DF * np.arange(PSD_NF)) / 1e6
    hour = (sec / 3600.0) % 24.0
    # Receiver noise floor, gently sloped so the band edges are distinguishable.
    p = -166.0 + 1.5 * (f_mhz - f_mhz.mean()) / 100.0
    p = p + rng.normal(0, 1.1, PSD_NF)
    for ch in CHANNELS:
        occ = max(_load(sensor, ch, hour), _radar(day_index, sec, ch))
        if occ <= 0.02:
            continue
        # A 10 MHz channel with soft shoulders, lifted by its occupancy.
        edge = np.clip(1.0 - (np.abs(f_mhz - ch) / 5.0) ** 8, 0, 1)
        p = p + edge * (26.0 * occ)
    return np.clip(p, PSD_QMIN + 0.5, PSD_QMAX - 0.5)


def write_psd(dirpath):
    """PSD CSVs -> psd_ingest.py -> psd.duckdb (the per-sensor spectrum layer)."""
    os.makedirs(dirpath, exist_ok=True)
    written = 0
    for sensor in SENSORS:
        for di, day in enumerate(DAYS[:2]):        # two days is plenty to pan
            rng = np.random.default_rng(abs(hash((sensor, day))) % (2 ** 32))
            step = 86400 // PSD_PER_DAY
            lines = ["datetime," + ",".join(f"b{i}" for i in range(PSD_NF))]
            for k in range(PSD_PER_DAY):
                sec = k * step
                hh, mm = sec // 3600, (sec % 3600) // 60
                spec = _spectrum(sensor, di, sec, rng)
                lines.append(f"{day} {hh:02d}:{mm:02d}:00,"
                             + ",".join(f"{v:.2f}" for v in spec))
            out = os.path.join(dirpath, f"{day}_{sensor}_max.csv")
            with open(out, "w", newline="") as f:
                f.write("\n".join(lines) + "\n")
            written += 1
    return written


def write_pfp(dirpath):
    """PFP CSVs -> pfp_ingest.py -> pfp.duckdb (the frame-timing layer)."""
    os.makedirs(dirpath, exist_ok=True)
    pos = np.arange(PFP_NPOS) / PFP_NPOS            # 0..1 across a 10 ms frame
    written = 0
    for sensor in SENSORS:
        for di, day in enumerate(DAYS[:2]):
            rng = np.random.default_rng(abs(hash((sensor, day, "pfp"))) % (2 ** 32))
            step = 86400 // PFP_PER_DAY
            lines = ["datetime,frequency,"
                     + ",".join(f"p{i}" for i in range(PFP_NPOS))]
            for k in range(PFP_PER_DAY):
                sec = k * step
                hh, mm = sec // 3600, (sec % 3600) // 60
                for ch in (3565.0, 3645.0):     # one quiet channel, one busy
                    occ = max(_load(sensor, ch, (sec / 3600.0) % 24.0),
                              _radar(di, sec, ch))
                    # TDD duty cycle: downlink for the first ~65% of the frame.
                    on = (pos < 0.65).astype(float)
                    frame = -118.0 + rng.normal(0, 1.2, PFP_NPOS)
                    frame = frame + on * (70.0 * occ)
                    frame = np.clip(frame, PFP_QMIN + 0.5, PFP_QMAX - 0.5)
                    lines.append(f"{day} {hh:02d}:{mm:02d}:00,{ch * 1e6:.0f},"
                                 + ",".join(f"{v:.2f}" for v in frame))
            out = os.path.join(dirpath, f"PFP_{day}_{sensor}_max_peak.csv")
            with open(out, "w", newline="") as f:
                f.write("\n".join(lines) + "\n")
            written += 1
    return written


# ---- running the real ingest scripts ----------------------------------

def db_dir():
    """Where serve.py will look. Same resolution serve.py, atlas.py and
    verify.py use, so the demo cannot land somewhere the server never reads --
    including the abspath, without which a relative ATLAS_DB_DIR resolves against
    whatever directory each step is run from and the demo builds one half of
    itself into a folder the server never opens."""
    return os.path.abspath(os.environ.get("ATLAS_DB_DIR") or ROOT)


def db_path(name, var):
    return os.environ.get(var) or os.path.join(db_dir(), name)


def run(argv, env):
    return subprocess.run(argv, env=env, cwd=ROOT).returncode == 0


def build_iq(env):
    print("Generating synthetic SigMF capture ...")
    meta_path = write_sigmf(synth())
    print(f"  wrote {meta_path}")
    print("Running ingest/iq_ingest.py -> iq.duckdb ...")
    return run([sys.executable, os.path.join(INGEST, "iq_ingest.py"),
                SAMPLE_DIR, "--dataset", "demo"], env)


def build_cbrs(env, force=False):
    if force:
        # psd_ingest and pfp_ingest are resumable: they skip days already in
        # the database. Left in place, --force would silently rebuild nothing
        # for two of the three layers. build_db.py drops its own file.
        for p in existing_cbrs():
            os.remove(p)
            print(f"  removed {p}")

    summaries = os.path.join(CBRS_DIR, "summaries", "Summaries_demo.csv")
    psd_dir = os.path.join(CBRS_DIR, "spectra")
    pfp_dir = os.path.join(CBRS_DIR, "frames")

    print("Generating synthetic CBRS exports ...")
    n = write_summaries(summaries)
    print(f"  wrote {summaries}\n    ({n:,} rows: {len(SENSORS)} sensors x "
          f"{len(CHANNELS)} channels x {len(DAYS)} days)")
    print(f"  wrote {write_psd(psd_dir)} PSD CSVs under {psd_dir}")
    print(f"  wrote {write_pfp(pfp_dir)} PFP CSVs under {pfp_dir}")

    print("\nRunning ingest/build_db.py -> spectrum.duckdb ...")
    if not run([sys.executable, os.path.join(INGEST, "build_db.py"),
                "--csv-dir", os.path.dirname(summaries)], env):
        return False
    # psd_ingest and pfp_ingest take one sensor at a time, which is also how a
    # real pull is driven: a sensor is days of files, and you add them as they
    # download rather than waiting for the whole set.
    for sensor in SENSORS:
        print(f"\nRunning ingest/psd_ingest.py {sensor} -> psd.duckdb ...")
        if not run([sys.executable, os.path.join(INGEST, "psd_ingest.py"),
                    sensor, "--root", psd_dir], env):
            return False
        print(f"\nRunning ingest/pfp_ingest.py {sensor} -> pfp.duckdb ...")
        if not run([sys.executable, os.path.join(INGEST, "pfp_ingest.py"),
                    sensor, "--root", pfp_dir], env):
            return False
    return True


def existing_cbrs():
    return [p for p in (db_path("spectrum.duckdb", "SPECTRUM_DB"),
                        db_path("psd.duckdb", "PSD_DB"),
                        db_path("pfp.duckdb", "PFP_DB"))
            if os.path.exists(p)]


def main():
    ap = argparse.ArgumentParser(
        description="Build the demo databases with no downloads.")
    ap.add_argument("--iq", action="store_true",
                    help="only the IQ capture (iq.duckdb)")
    ap.add_argument("--cbrs", action="store_true",
                    help="only the CBRS layers (spectrum/psd/pfp.duckdb)")
    ap.add_argument("--force", action="store_true",
                    help="overwrite CBRS databases that already exist")
    args = ap.parse_args()
    want_iq = args.iq or not args.cbrs
    want_cbrs = args.cbrs or not args.iq

    # Every ingest script resolves its own database the same way; setting the
    # per-database variables here means one answer for all of them even when
    # the caller has only set some.
    env = {**os.environ,
           "IQ_DB": db_path("iq.duckdb", "IQ_DB"),
           "SPECTRUM_DB": db_path("spectrum.duckdb", "SPECTRUM_DB"),
           "PSD_DB": db_path("psd.duckdb", "PSD_DB"),
           "PFP_DB": db_path("pfp.duckdb", "PFP_DB")}

    if want_cbrs and not args.force:
        # build_db.py REPLACES spectrum.duckdb wholesale, and psd/pfp would merge
        # demo sensors into real ones. Neither is acceptable to do silently to
        # someone who has spent hours downloading the real thing.
        clash = existing_cbrs()
        if clash:
            print("These CBRS databases already exist:", file=sys.stderr)
            for p in clash:
                print(f"  {p}", file=sys.stderr)
            print("\nNot overwriting them: building the demo on top would replace\n"
                  "spectrum.duckdb and merge demo sensors into psd/pfp.\n"
                  "  python examples/make_sample.py --force   # replace them\n"
                  "  python examples/make_sample.py --iq      # leave them alone",
                  file=sys.stderr)
            if not want_iq:
                return 1
            want_cbrs = False
            print(file=sys.stderr)

    if want_iq and not build_iq(env):
        return 1
    if want_cbrs and not build_cbrs(env, args.force):
        return 1

    print("\nDone. Databases in", db_dir())
    for name, var in (("iq.duckdb", "IQ_DB"),
                      ("spectrum.duckdb", "SPECTRUM_DB"),
                      ("psd.duckdb", "PSD_DB"), ("pfp.duckdb", "PFP_DB")):
        p = db_path(name, var)
        size = f"{os.path.getsize(p) / 1e6:8.1f} MB" if os.path.exists(p) \
            else "  absent  "
        print(f"  {size}  {name}")
    print("\nNow run:  python serve.py")
    print("Then open http://127.0.0.1:8090 -- the Source dropdown has the IQ "
          "capture\nand the CBRS sensors; the statistic buttons and the "
          "PSD/PFP layers work on\nthe sensors.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
